import LargeWithAppLinksAndSocial from "@/components/Footer";

import WithSubnavigation from "@/components/navbar";
import Head from "next/head";
import Search from "@/components/search/Search";
import { BrowserRouter } from "react-router-dom";
import mainReducer, { mainInitialState, StateProvider } from "./../reducers";

const Home = () => {
  return (
    <>
      <BrowserRouter>
        <StateProvider reducer={mainReducer} initialState={mainInitialState}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <WithSubnavigation />
            <Search small={undefined} showSideBar={undefined} />
            <LargeWithAppLinksAndSocial />
          </main>
        </StateProvider>
      </BrowserRouter>
    </>
  );
};

export default Home;
