import LargeWithAppLinksAndSocial from "@/components/Footer";
import WithSubnavigation from "@/components/navbar";
import Head from "next/head";
import { NextPageContext } from "next";

export default function Home(props: any) {
  console.log(props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithSubnavigation />
      </main>
    </>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  const data = context.query;
  return { props: { data } };
}
